CREATE TABLE posts (
 id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(255) NOT NULL,
 body TEXT NOT NULL,
 thumbnail VARCHAR(255) NULL,
 date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 category_id INT(11) UNSIGNED DEFAULT NOT NULL,
 author_id INT(11) UNSIGNED NOT NULL,
 is_featured TINYINT(1) NOT NULL,
 ALTER TABLE posts ADD CONSTRAINT FK_blog_category FOREIGN KEY(category_id) REFERENCES categories(id)ON DELETE SET NULL,
 ALTER TABLE posts ADD CONSTRAINT FK_blog_author FOREIGN KEY(author_id)REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
